datasetPath: D:\Documents\Repos\CVProjectBasedLearning\Slam\data\rgbd_dataset_freiburg1_xyz\rgb
resultsSavePath: Slam\results
cameraParamsFile: D:\Documents\Repos\CVProjectBasedLearning\Slam\data\rgbd_dataset_freiburg1_xyz\intrinsics.json
