dataPath: D:\Documents\Repos\CVProjectBasedLearning\VisualOdometry\data\KITTI_sequence_2\image_l
gtPosesPath: D:\Documents\Repos\CVProjectBasedLearning\VisualOdometry\data\KITTI_sequence_2\poses.txt
resultsSavePath: D:\Documents\Repos\CVProjectBasedLearning\VisualOdometry\VisualOdometryResults
cameraParamsFile: D:\Documents\Repos\CVProjectBasedLearning\VisualOdometry\data\KITTI_sequence_2\calib.txt