dataPath: D:\Documents\Repos\CVProjectBasedLearning\SfM\data\images
# gtPosesPath: D:\Documents\Repos\CVProjectBasedLearning\SfM\data\
resultsSavePath: D:\Documents\Repos\CVProjectBasedLearning\SfM\sfmResults
cameraParamsFile: D:\Documents\Repos\CVProjectBasedLearning\SfM\data\intrinsics.json